export interface SignUp {
  id: number;
  name: string,
  email: string,
  password: string
}
export interface Login {
  email: string,
  password: string
}

export interface Product {
  id: number;           // optional - will be auto-generated by JSON server
  name: string;          // product name
  price: number;         // product price
  category: string;      // e.g., "Bracelet", "Ring"
  color: string;         // e.g., "Gold", "Silver"
  description: string;   // detailed info
  image: string;         // image URL
}